In [2]:
import numpy as np

## Datatypes & Attributes 

In [3]:
# Numpy's main datatype is ndarray (n dimensional array).
array1 = np.array([1, 2, 3, 4, 5]) 
array1

array([1, 2, 3, 4, 5])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array2 = np.array([[1, 2, 3], [4, 5.1, 6]]) 
array2

array([[1. , 2. , 3. ],
       [4. , 5.1, 6. ]])

In [6]:
array3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [7]:
array1.shape

(5,)

In [8]:
array2.shape # The shape of the array is a tuple that indicates the number of elements along each dimension. For `array2`, which is a 2D array, the shape will be (2, 3), meaning it has 2 rows and 3 columns.

(2, 3)

In [9]:
array3.shape # The shape of `array3`, which is a 3D array, will be (2, 2, 3), indicating it has 2 blocks, each containing 2 rows and 3 columns.

(2, 2, 3)

In [10]:
array1.ndim, array2.ndim, array3.ndim # The `ndim` attribute returns the number of dimensions (or axes) of the array. For `array1`, it will return 1, for `array2` it will return 2, and for `array3` it will return 3.

(1, 2, 3)

In [11]:
array1.dtype, array2.dtype, array3.dtype # The `dtype` attribute returns the data type of the elements in the array. For all three arrays, it will return `int64` (or `int32` depending on the system), indicating that the elements are integers.

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
array1.size, array2.size, array3.size # The `size` attribute returns the total number of elements in the array. For `array1`, it will return 5, for `array2` it will return 6, and for `array3` it will return 12.

(5, 6, 12)

In [13]:
type(array1), type(array2), type(array3) # The `type` function returns the type of the object. For all three arrays, it will return `<class 'numpy.ndarray'>`, indicating that they are Numpy arrays.

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# Create a dataframe from numpy array

In [14]:
import pandas as pd

df = pd.DataFrame(array2)
df

,0,1,2
0,1.0,2.0,3.0
1,4.0,5.1,6.0


In [20]:
array4 = np.random.randint(0, 10, size=(3, 4)) # Create a 3x4 array of random integers between 0 and 10
array4

array([[1, 9, 9, 6],
       [6, 7, 0, 8],
       [8, 5, 6, 6]])

In [19]:
array4.shape # The shape of `array4` will be (3, 4), indicating it has 3 rows and 4 columns.

(3, 4)

In [26]:
np.random.seed(42) # Set the random seed for reproducibility
array5 = np.random.randint(0, 10, size=(3, 4)) # Create another 3x4 array of random integers between 0 and 10
array5

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]])

## Viewing Arrays and Matrices

In [27]:
np.unique(array5) # The `np.unique` function returns the sorted unique elements of an array. For `array5`, it will return an array containing the unique integers present in `array5`.

array([2, 3, 4, 6, 7, 9])

In [28]:
array1, array2, array3 

(array([1, 2, 3, 4, 5]),
 array([[1. , 2. , 3. ],
        [4. , 5.1, 6. ]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]))

In [32]:
array1[0], # Access the first element of `array1`, which is 1.

(np.int64(1),)

In [33]:
array2[0], # Access the second element of `array2`, which is 5.

(array([1., 2., 3.]),)

In [35]:
 array3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
array3[:2, :2, :2] # Access the first two blocks, first two rows, and first two columns of `array3`. This will return a 2x2x2 sub-array containing the elements from the specified slices.

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

## Manipulating & Comparing  Arrays

### Arithmetic

In [43]:
array1 = np.array([1, 2, 3]) # Create a 1D array with elements from 1 to 3
array1

array([1, 2, 3])

In [41]:
ones = np.ones((3)) # Create a col array filled with ones
ones

array([1., 1., 1.])

In [44]:
array1 + ones

array([2., 3., 4.])

In [45]:
array1 - ones

array([0., 1., 2.])

In [46]:
array2

array([[1. , 2. , 3. ],
       [4. , 5.1, 6. ]])

In [ ]:
array1 * array2 # Element-wise multiplication of `array1` and `array2`. Since `array1` is 1D and `array2` is 2D, Numpy will broadcast `array1` across the rows of `array2`, resulting in a new 2D array where each element of `array1` multiplies the corresponding row of `array2`.

array([[ 1. ,  4. ,  9. ],
       [ 4. , 10.2, 18. ]])

In [48]:
array1/ones

array([1., 2., 3.])

In [ ]:
array2 / array1 # Element-wise division of `array2` by `array1`. Similar to multiplication, Numpy will broadcast `array1` across the rows of `array2`, resulting in a new 2D array where each element of `array2` is divided by the corresponding element of `array1`.

array([[1.  , 1.  , 1.  ],
       [4.  , 2.55, 2.  ]])

In [50]:
array2 // array1 # Element-wise floor division of `array2` by `array1`. Similar to the multiplication operation, Numpy will broadcast `array1` across the rows of `array2`, resulting in a new 2D array where each element of `array2` is divided by the corresponding element of `array1`, and the result is floored to the nearest integer.

array([[1., 1., 1.],
       [4., 2., 2.]])

In [52]:
array2 ** 2 # Element-wise exponentiation of `array2`. Each element of `array2` is raised to the power of 2, resulting in a new 2D array where each element is the square of the corresponding element in `array2`.

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 26.01, 36.  ]])

In [ ]:
array1 % 2 # Element-wise modulus operation on `array1`. This will return a new array where each element is the remainder of the corresponding element in `array1` divided by 2.

array([1, 0, 1])